kubectl delete -f k8s-clients.yaml
kubectl delete -f k8s-books.yaml
kubectl delete -f k8s-cart.yaml
kubectl delete -f k8s-storage.yaml
kubectl delete -f k8s-orders.yaml
kubectl delete -f k8s-payment.yaml
kubectl delete -f k8s-dynapay.yaml
kubectl delete -f k8s-ingest.yaml
kubectl delete -f k8s-bookstore.yaml