apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: ihudak/dt-orders-service:latest
          ports:
            - containerPort: 8080
            - containerPort: 5005
          env:
            - name: DT_SERVER_PORT
              value: "8080"
            - name: DT_MYSQL_SERVER
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: mysql_server
            - name: DT_MYSQL_PORT
              value: "3306"
            - name: DT_MYSQL_DBNAME
              value: none # DB NAME HERE
            - name: DT_MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: bookstore-secret
                  key: mysql-user-name
            - name: DT_MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: bookstore-secret
                  key: mysql-user-pass
            - name: DT_PG_SERVER
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: pgdb_server
            - name: DT_PG_PORT
              value: "5432"
            - name: DT_PG_DBNAME
              value: dt_books_orders # DB NAME HERE
            - name: DT_PG_USER
              valueFrom:
                secretKeyRef:
                  name: bookstore-secret
                  key: pgdb-user-name
            - name: DT_PG_PASS
              valueFrom:
                secretKeyRef:
                  name: bookstore-secret
                  key: pgdb-user-pass
            - name:   DT_CLIENTS_SERVER
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: clients_svc
            - name:   DT_BOOKS_SERVER
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: books_svc
            - name:   DT_CART_SERVER
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: cart_svc
            - name:   DT_STORAGE_SERVER
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: storage_svc
            - name:   DT_ORDERS_SERVER
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: orders_svc
            - name:   DT_PAYMENT_SERVER
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: payments_svc
            - name:   DT_DYNAPAY_SERVER
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: dynapay_svc
            - name:   DT_RATINGS_SERVER
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: ratings_svc
          resources:
            limits:
              cpu: 900m
              memory: 1Gi
            requests:
              cpu: 400m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: orders-svc
spec:
  selector:
    app: orders
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30005
    - name: debug
      port: 5005
      protocol: TCP
      targetPort: 5005
      nodePort: 32005
