apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: ihudak/dt-payment-service:arm64
          ports:
            - containerPort: 8080
            - containerPort: 5005
          env:
            - name: DT_SERVER_PORT
              value: "8080"
            - name: DT_MYSQL_SERVER
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: mysql_server
            - name: DT_MYSQL_PORT
              value: "3306"
            - name: DT_MYSQL_DBNAME
              value: dt_books_payments # DB NAME HERE
            - name: DT_MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: bookstore-secret
                  key: mysql-user-name
            - name: DT_MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: bookstore-secret
                  key: mysql-user-pass
            - name: DT_PG_SERVER
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: pgdb_server
            - name: DT_PG_PORT
              value: "5432"
            - name: DT_PG_DBNAME
              value: none # DB NAME HERE
            - name: DT_PG_USER
              valueFrom:
                secretKeyRef:
                  name: bookstore-secret
                  key: pgdb-user-name
            - name: DT_PG_PASS
              valueFrom:
                secretKeyRef:
                  name: bookstore-secret
                  key: pgdb-user-pass
            - name:   DT_CLIENTS_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: clients_svc
            - name:   DT_BOOKS_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: books_svc
            - name:   DT_CART_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: cart_svc
            - name:   DT_STORAGE_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: storage_svc
            - name:   DT_ORDERS_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: orders_svc
            - name:   DT_PAYMENT_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: payments_svc
            - name:   DT_DYNAPAY_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: dynapay_svc
            - name:   DT_RATINGS_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: bookstore-configmap
                  key: ratings_svc
          resources:
            limits:
              cpu: 700m
              memory: 640Mi
            requests:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: payment-svc
spec:
  selector:
    app: payment
  type: LoadBalancer
  ports:
    - name: http
      port: 86
      protocol: TCP
      targetPort: 8080
      nodePort: 30006
    - name: debug
      port: 5006
      protocol: TCP
      targetPort: 5005
      nodePort: 32006