# kubectl apply -f k8s-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: bookstore-secret
type: Opaque
data:
  mysql-user-name: cm9vdA==
  mysql-user-pass: cEBzc3cwckQh
  pgdb-user-name: cGd1c2Vy
  pgdb-user-pass: cEBzc3cwckQh
  oneagent-token: <base64-ed OneAgent token, concatenated if multiline>
  otel-token: <base64-ed Otel token, concatenated if multiline>
